[workspace]
authors = ["lkless <leakless21@gmail.com>"]
channels = ["conda-forge"]
name = "traffic-monitor-resources"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
run-all-evaluations = "python evaluation_tools/run_all_visualizations.py"
run-vehicle-detection = "python evaluation_tools/visualize_vehicle_detection.py"
run-plate-detection = "python evaluation_tools/visualize_plate_detection.py"
run-ocr-benchmarks = "python evaluation_tools/visualize_ocr_benchmarks.py"
run-comprehensive-tables = "python evaluation_tools/generate_comprehensive_tables.py"
test-imports = "python -c 'import pandas, matplotlib, seaborn; print(\"All packages available\")'"

[dependencies]
python = ">=3.13.5,<3.14"

[pypi-dependencies]
pandas = ">=2.3.0, <3"
matplotlib = ">=3.10.3, <4"
seaborn = ">=0.13.2, <0.14"
