[workspace]
authors = ["lkless <leakless21@gmail.com>"]
channels = ["conda-forge"]
name = "traffic-monitor-resources"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
run-ocr-evals = "python evaluation_tools/run_all_ocr_evaluations.py"
run-all-visual = "F:/hok/DATN/Project/traffic-monitor-resources/.pixi/envs/default/python.exe F:/hok/DATN/Project/traffic-monitor-resources/evaluation_tools/run_all_visualizations.py"

[dependencies]
python = ">=3.13.5,<3.14"

[pypi-dependencies]
matplotlib = ">=3.10.3, <4"
seaborn = ">=0.13.2, <0.14"
pandas = ">=2.3.0, <3"
scikit-learn = ">=1.7.0, <2"
loguru = ">=0.7.3, <0.8"
